### ISSUE TITLE
Hope to see option to be added for Subtotal to appear at the bottom too

### ISSUE THREAD

**Issue by hkbeer** [nagarajanchinnasamy/pivottable-subtotal-renderer#49] opened 2017-09-20 08:37 UTC
Hello this is a great tool... thank you so much.
Would be great if you are successful in  adding an option to show Subtotal at the bottom as well.

Hope to see this happen soon. 
Again, great work , thanks

**Comment by nagarajanchinnasamy** [comment] 2017-09-22 07:23
Thanks for your feedback 👍 

This is a duplicate of issue #12 . Please track the progress there. Am closing this issue as duplicate.

**Closed by nagarajanchinnasamy** 2017-09-22 07:23 UTC
