### ISSUE TITLE
RangeError: Maximum call stack size exceeded when using 'Table With Subtotal Heatmap' renderer

### ISSUE THREAD

**Issue by zam6ak** [nagarajanchinnasamy/pivottable-subtotal-renderer#15] opened 2016-11-08 21:53 UTC
I have a data set with approx 14,000 rows (array of arrays), each row with 5 items.

the usage is straight forward, but if I use heatmap renderer it crashes:
```
$("#pivot1").pivot(data, {
    dataClass: $.pivotUtilities.SubtotalPivotData, 
    rows: ['Source', 'Order Type', 'Order Date', 'Customer & Order Description'],
    cols: ['Order Status'],
    aggregator: count()(['Order Date']),
    renderer: renderers['Table With Subtotal Heatmap'], // crashes
    //renderer: renderers['Table With Subtotal'],       // works
    rendererOptions: {
        collapseRowsAt: 'Order Date'
    }
});
```
Here is the error:

```
pivot.coffee:551 RangeError: Maximum call stack size exceeded
    at Function.ga [as find] (jquery.min.js:2)
    at r.fn.init.find (jquery.min.js:2)
    at forEachCell (pivot.coffee:898)
    at pivot.coffee:903
    at r.fn.init.$.fn.heatmap (pivot.coffee:908)
    at Object.Table With Subtotal Heatmap [as renderer] (subtotal.coffee:630)
    at r.fn.init.$.fn.pivot (pivot.coffee:549)
    at HTMLDocument.<anonymous> (report:176)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
$.fn.pivot @ pivot.coffee:551
(anonymous) @ report:176
j @ jquery.min.js:2
k @ jquery.min.js:2
```

**Comment by nagarajanchinnasamy** [comment] 2016-11-14 11:55
Hi did u try built-in "Heatmap" renderer? Does it work?

**Comment by nagarajanchinnasamy** [comment] 2016-11-17 08:07
Hi could you please share the dataset - with adequate masking.... so that I can reproduce the error?

**Comment by zam6ak** [comment] 2016-11-17 14:23
I tried to anonymize the data set so I can share it, but its too much...
But I found several data sets on the Internet....
I am going to try companies data set (last one) from here: http://jsonstudio.com/resources/
and see if I can reproduce..

Using just Heatmap renderer was weird...Worked 2 out of 10 times I tried (just reloading the page, no other changes).....

**Comment by nagarajanchinnasamy** [comment] 2016-11-17 19:15
Sure Thanks.

But, if the Heatmap renderer is failing on your dataset... then I suggest you take it up with the base/upstream PivotTable.js project first --- For heatmap functionality I don;t do anything other than just calling the base project's heatmap rendering...!!!

**Comment by nagarajanchinnasamy** [comment] 2016-11-25 20:11
@zam6ak  could you check with base `pivottable.js` package to confirm if the issue is with `subtotoal` plugin or not???!!!

**Comment by zam6ak** [comment] 2016-11-28 21:53
Apologies for delay on this.
I confirmed that issue exists even when using 'Heatmap' renderer from base project.
I filed the issue: https://github.com/nicolaskruchten/pivottable/issues/585

**Comment by nagarajanchinnasamy** [comment] 2016-12-02 13:37
@zam6ak Will keep this issue open, till we confirm that the issue is resolved. Sorry I misread your message that you fixed it...instead of *filed* it! Hence the closure and reopening of the issue :)

**Comment by nagarajanchinnasamy** [comment] 2016-12-14 08:21
Closing this issue as per the details in https://github.com/nicolaskruchten/pivottable/issues/585

**Closed by nagarajanchinnasamy** 2016-12-14 08:21 UTC
